site_name: 書籍『ゆるやかに学ぶ C 言語』オンライン公式資料・サポート
site_author: Ryo Suzuki
site_description: "書籍『ゆるやかに学ぶ C 言語』のオンライン公式資料・サポート" 

# Copyright
copyright: Copyright (c) 2026 Ryo Suzuki

# Theme
theme:
  name: material
  language: ja
  font:
    text: IBM Plex Sans JP
    code: Roboto Mono
  palette:
    scheme: lecture
  logo: 'assets/images/code-white-48dp.svg'
  features:
  - navigation.instant
  - navigation.top
  - search.suggest
  - search.highlight
  - content.code.annotate
  - content.code.copy
  - content.tooltips
  plugins:
  - search:
      lang:
        - ja
extra_css:
  - "https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css"
  - stylesheets/extra.css
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - pymdownx.snippets
  - toc:
      permalink: true
      toc_depth: 3
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences:
      preserve_tabs: true
  - pymdownx.keys
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

# Page tree
nav:
  - 目次: index.md
  - プログラムを動かす準備:
    - Wandbox: setup/wandbox.md
    - Codespaces: setup/codespaces.md
    - Windows: setup/windows.md
    - macOS: setup/macos.md
    - Ubuntu: setup/ubuntu.md
  - サンプルコード:
    - 第 1 章 プログラミングの基礎: code/1.md
    - 第 2 章 基本的な計算と結果の出力: code/2.md
    - 第 3 章 変数とキーボードからの入力: code/3.md
    - 第 4 章 比較と条件分岐: code/4.md
    - 第 5 章 計算による変数の値の変更: code/5.md
    - 第 6 章 文字を扱う: code/6.md
    - 第 7 章 処理の繰り返し: code/7.md
    - 第 8 章 制御のための文と演算子: code/8.md
    - 第 9 章 発展的な型: code/9.md
    - 第 10 章 関数の呼び出しと定義: code/10.md
    - 第 11 章 const とマクロ: code/11.md
    - 第 12 章 値渡しとポインタ渡し: code/12.md
    - 第 13 章 時間と乱数: code/13.md
    - 第 14 章 配列: code/14.md
    - 第 15 章 文字列: code/15.md
    - 第 16 章 中級者向けの機能: code/16.md
    - 第 17 章 構造体: code/17.md
    - 第 18 章 ソート: code/18.md
    - 第 19 章 動的メモリ確保: code/19.md
    - 第 20 章 ファイルの読み書き: code/20.md
    - 第 21 章 画像処理: code/21.md
  - 付録:
    - 付録 1. 記号の名称と読み方: appendix/symbols.md
    - 付録 2. キーワード一覧: appendix/keywords.md
    - 付録 3. コンパイラ・オプション: appendix/compiler-options.md
    - 付録 4. 演算子の優先順位: appendix/operator-precedence.md
    - 付録 5. ASCII コード表: appendix/ascii.md
